---
#
AWSTemplateFormatVersion: '2010-09-09'
Description: AWS IoT Button Demo
Parameters:
  ServiceName:
    Description: Becomes the short hostname used in DNS, Naming, Comments, and other
      things.
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"

  
Resources:
  ButtonThing:
    Type: AWS::IoT::Thing
    Properties: 
      AttributePayload :
        Attributes :
          ServiceName : 
            Ref: "ServiceName"
      #ThingName: String



Outputs: {}
