version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn packag
      - aws s3 cp target/lambda-java-example-0.0.1-SNAPSHOT.jar s3://mediaworks-lambdajavacode/LambdaJavaBuild/target/ 
artifacts:
  files:
    - target/lambda-java-example-0.0.1-SNAPSHOT.jar
